// src/lib/quotes.ts

export interface Quote {
  text: string;
  author: string;
  isAi?: boolean;
}

export const quotes: Quote[] = [
  { text: "The only way to define your limits is by going beyond them.", author: "Arthur C. Clarke" },
  { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "The clock is ticking. Are you becoming the person you want to be?", author: "Greg Plitt" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Anonymous" },
  { text: "Success is what happens after you have survived all of your mistakes.", author: "Anamika Mishra" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "You must do the thing you think you cannot do.", author: "Eleanor Roosevelt" },
  { text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson" },
  { text: "Your body is the only place you have to live. Take care of it.", author: "Jim Rohn" },
  { text: "A champion is someone who gets up when they can't.", author: "Jack Dempsey" },
  { text: "The difference between the impossible and the possible lies in a person's determination.", author: "Tommy Lasorda" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "The only bad workout is the one that didn't happen.", author: "Anonymous" },
  { text: "Fitness is not about being better than someone else. It's about being better than you were yesterday.", author: "Anonymous" },
  { text: "It's going to be a journey. It's not a sprint to get in shape.", author: "Kerri Walsh Jennings" },
  { text: "The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it.", author: "Arnold Schwarzenegger" },
  { text: "The last three or four reps is what makes the muscle grow. This area of pain divides the champion from someone else who is not a champion.", author: "Arnold Schwarzenegger" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "I've failed over and over and over again in my life and that is why I succeed.", author: "Michael Jordan" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Anonymous" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "Success starts with self-discipline.", author: "Anonymous" },
  { text: "Great things never came from comfort zones.", author: "Anonymous" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Anonymous" },
  { text: "Sometimes later becomes never. Do it now.", author: "Anonymous" },
  { text: "Dream it. Wish it. Do it.", author: "Anonymous" },
  { text: "Success doesn’t just find you. You have to go out and get it.", author: "Anonymous" },
  { text: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Anonymous" },
  { text: "Dream bigger. Do bigger.", author: "Anonymous" },
  { text: "Don’t stop until you’re proud.", author: "Anonymous" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Anonymous" },
  { text: "Do something today that your future self will thank you for.", author: "Anonymous" },
  { text: "Little things make big days.", author: "Anonymous" },
  { text: "It’s going to be hard, but hard does not mean impossible.", author: "Anonymous" },
  { text: "Don’t wait for opportunity. Create it.", author: "Anonymous" },
  { text: "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", author: "Anonymous" },
  { text: "The key to success is to focus on goals, not obstacles.", author: "Anonymous" },
  { text: "Dream it. Believe it. Build it.", author: "Anonymous" },
  { text: "The level of your success is limited only by your imagination and hard work.", author: "Anonymous" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { text: "Your health is an investment, not an expense.", author: "Anonymous" },
  { text: "Train like a beast, look like a beauty.", author: "Anonymous" },
  { text: "Sweat is just fat crying.", author: "Anonymous" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Persistence is the quality of winners.", author: "Anonymous" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "Progress, not perfection.", author: "Anonymous" },
  { text: "Focus on the goal, not the pain.", author: "Anonymous" },
  { text: "Consistency is more important than perfection.", author: "Anonymous" },
  { text: "You are stronger than you think.", author: "Anonymous" },
  { text: "Small progress is still progress.", author: "Anonymous" },
  { text: "Your only competition is the person you were yesterday.", author: "Anonymous" },
  { text: "Get comfortable with being uncomfortable.", author: "Anonymous" },
  { text: "The body achieves what the mind believes.", author: "Anonymous" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "Results take time. Stay patient.", author: "Anonymous" },
  { text: "Exercise is a celebration of what your body can do.", author: "Anonymous" },
  { text: "Don't wish for it, work for it.", author: "Anonymous" },
  { text: "The best project you'll ever work on is you.", author: "Anonymous" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "The struggle you're in today is developing the strength you need for tomorrow.", author: "Robert Tew" },
  { text: "The pain of discipline is far less than the pain of regret.", author: "Anonymous" },
  { text: "What seems impossible today will one day become your warm-up.", author: "Anonymous" },
  { text: "Suffer the pain of discipline or suffer the pain of regret.", author: "Jim Rohn" },
  { text: "If it doesn't challenge you, it doesn't change you.", author: "Fred DeVito" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { text: "Keep showing up.", author: "Anonymous" },
  { text: "Today I will do what others won't, so tomorrow I can do what others can't.", author: "Jerry Rice" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "The mind always fails first, not the body. The secret is to make your mind work for you, not against you.", author: "Arnold Schwarzenegger" },
  { text: "To be a champion, you have to believe in yourself when no one else will.", author: "Sugar Ray Robinson" },
  { text: "One day or Day One. You decide.", author: "Anonymous" },
  { text: "You're only one workout away from a good mood.", author: "Anonymous" },
  { text: "Health is the greatest wealth.", author: "Virgil" },
  { text: "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.", author: "John F. Kennedy" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Don't quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali" },
  { text: "I hated every minute of training, but I said, 'Don't quit.'", author: "Muhammad Ali" },
  { text: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
  { text: "Strength is life. Weakness is death.", author: "Swami Vivekananda" },
  { text: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Your life is your message to the world. Make sure it's inspiring.", author: "Anonymous" },
  { text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { text: "The neural pathways to greatness are paved with heavy sets.", author: "Aura AI", isAi: true },
  { text: "Your body is an algorithm; consistency is the optimization variable.", author: "Aura AI", isAi: true },
  { text: "Hypertrophy is the physical manifestation of discipline.", author: "Aura AI", isAi: true },
  { text: "Regression is just a signal for a more powerful reboot.", author: "Aura AI", isAi: true },
  { text: "Volume is the currency of growth. Spend it wisely.", author: "Aura AI", isAi: true },
];

export function getRandomQuote(): Quote {
  return quotes[Math.floor(Math.random() * quotes.length)];
}
